#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long;
use Cwd;
use File::Random qw/random_file/;

#TODO: real options
#TODO: choose list of dirs (multiple -d option)


my $pat = '^.+$';

GetOptions(
    'p|pattern=s' => \$pat,
    #'directory=s' => $dir
    );

my @dirs = (shift @ARGV or cwd());

for my $dir (@dirs) {
my $random_file = random_file(-dir       => $dir,
                              -check => qr/$pat/,
                              -recursive => 1);
print "$random_file\n";
}
